Change storage file to track2
Azure-Samples/storage-file-dotnet-getting-started pull request #7
Opened 2021-03-26 08:53 UTC by Luyunmt

SDK Updated List

Azure.Storage.Blobs
Azure.Storage.Common
Azure.Storage.Files.Shares

2021-05-13 09:23 UTC, v-xuto commented
@jongio - Can you help ping the corresponding person to review this PR?

2021-08-31 09:55 UTC, v-xuto commented
@scottaddie, @AlexGhiondea, @kyle-patterson , @tg-msft, @amishra-dev - Could you help review this PR?

2021-09-28 01:34 UTC, v-xuto commented
@scottaddie, @AlexGhiondea, @kyle-patterson , @tg-msft, @amishra-dev - Could you help review this PR?

2021-10-09 09:49 UTC, v-xuto commented
@scottaddie, @AlexGhiondea, @kyle-patterson , @tg-msft, @amishra-dev - Could you help review this PR?

2021-10-25 06:02 UTC, v-xuto commented
@scottaddie, @AlexGhiondea, @kyle-patterson , @tg-msft, @amishra-dev - Could you help review this PR?

2021-10-29 17:30 UTC, christothes commented on FileStorage/GettingStarted.cs
> +                    Console.WriteLine("    - {0} (type: {1})", listItem.Name, listItem.GetType());
I think we should use IsDirectory here instead

```suggestion
                    // listItem type will be a file or directory
                    Console.WriteLine("    - {0} (IsDirectory: {1})", listItem.Name, listItem.IsDirectory);
```

2021-10-29 17:30 UTC, christothes commented on FileStorage/GettingStarted.cs
> +                */
Is this intentionally commented out?

2021-11-01 07:07 UTC, Tianyun-G commented
@christothes - I have updated ,please review.

2021-11-08 03:26 UTC, v-xuto commented
@christothes - We have updated by your comments, please rereview this PR.

2021-11-08 16:08 UTC, christothes commented
Please update to the latest released versions of the storage packages and clean up any unneeded dependencies from the project and packages.config.

2021-11-09 02:12 UTC, Tianyun-G commented
@christothes - I have updated , please review.

2021-11-16 02:17 UTC, v-xuto commented
@christothes - We have updated by your comments, please re-review this PR.

2021-11-18 19:05 UTC, christothes approved these changes

2021-11-18 19:05 UTC, christothes commented on FileStorage/Advanced.cs
> +            // Create a share client for interacting with the file service.
```suggestion
            // Create a share service client for interacting with the file service.
```

2021-11-18 19:05 UTC, christothes commented on FileStorage/packages.config
> +  <package id="Azure.Core" version="1.18.0" targetFramework="net472" />
remove?

2021-11-19 01:56 UTC, Tianyun-G commented on FileStorage/packages.config
> +  <package id="Azure.Core" version="1.18.0" targetFramework="net472" />
@christothes - I have removed, please review.

2021-11-19 18:26 UTC, christothes approved these changes

2021-11-22 22:03 UTC, scottaddie requested changes

2021-11-22 22:03 UTC, scottaddie commented on FileStorage/Advanced.cs
> +            ShareServiceClient shareServiceClient = new ShareServiceClient(storageConnectionString);
Prefer `var` when the type is obvious.

```suggestion
            var shareServiceClient = new ShareServiceClient(storageConnectionString);
```

2021-11-22 22:03 UTC, scottaddie commented on FileStorage/Advanced.cs
> +                ShareCorsRule corsRule = new ShareCorsRule
```suggestion
                var corsRule = new ShareCorsRule
```

2021-11-22 22:03 UTC, scottaddie commented on FileStorage/Advanced.cs
> +                await sampleDirectory.SetMetadataAsync(metadate);
```suggestion
                var metadata = new Dictionary<string, string> { {"key1", "value1"}, {"key2", "value2"} };
                await sampleDirectory.SetMetadataAsync(metadata);
```

2021-11-22 22:03 UTC, scottaddie commented on FileStorage/Advanced.cs
> +                ShareFileHttpHeaders headers = new ShareFileHttpHeaders()
```suggestion
                var headers = new ShareFileHttpHeaders
```

2021-11-22 22:03 UTC, scottaddie commented on FileStorage/Advanced.cs
> +                metadata.Add("key2", "value2");
```suggestion
                var metadata = new Dictionary<string, string> { {"key1", "value1"}, {"key2", "value2"} };
```

2021-11-22 22:03 UTC, scottaddie commented on FileStorage/Advanced.cs
> +            await shareClient.SetMetadataAsync(metaData);
```suggestion
            var metadata = new Dictionary<string, string> { {"key1", "value1"}, {"key2", "value2"} };
            await shareClient.SetMetadataAsync(metadata);
```

2021-11-23 07:58 UTC, Tianyun-G commented
@scottaddie - I have updated , please review.

2021-11-23 22:44 UTC, scottaddie approved these changes
This PR looks good after incorporating these suggestions.

2021-11-23 22:44 UTC, scottaddie commented on FileStorage/Advanced.cs
> +                    await foreach (ShareItem Share in shareList)
```suggestion
                    await foreach (ShareItem share in shareList)
```

2021-11-23 22:44 UTC, scottaddie commented on FileStorage/Advanced.cs
> +                        Console.WriteLine("Cloud Share name = {0}", Share.Name);
```suggestion
                        Console.WriteLine("Cloud Share name = {0}", share.Name);
```

2021-11-23 22:44 UTC, scottaddie commented on FileStorage/GettingStarted.cs
> +                ShareServiceClient shareServiceClient = new ShareServiceClient(storageConnectionString);
```suggestion
                var shareServiceClient = new ShareServiceClient(storageConnectionString);
```

2021-11-23 22:44 UTC, scottaddie commented on FileStorage/GettingStarted.cs
> +                BlobServiceClient blobServiceClient = new BlobServiceClient(storageConnectionString);
```suggestion
                var blobServiceClient = new BlobServiceClient(storageConnectionString);
```

2021-11-23 22:44 UTC, scottaddie commented on FileStorage/GettingStarted.cs
> +                AccountSasBuilder sas = new AccountSasBuilder
```suggestion
                var sas = new AccountSasBuilder
```

2021-11-23 22:44 UTC, scottaddie commented on FileStorage/GettingStarted.cs
> +                StorageSharedKeyCredential credential = new StorageSharedKeyCredential(storageAccountName, storageAccountKey);
```suggestion
                var credential = new StorageSharedKeyCredential(storageAccountName, storageAccountKey);
```

2021-11-23 22:44 UTC, scottaddie commented on FileStorage/GettingStarted.cs
> +                UriBuilder sasUri = new UriBuilder(shareFileClient.Uri)
```suggestion
                var sasUri = new UriBuilder(shareFileClient.Uri)
```

2021-11-23 22:44 UTC, scottaddie commented on FileStorage/GettingStarted.cs
> +                    HttpRange range = new HttpRange(startOffset, textToStream.Length);
```suggestion
                    var range = new HttpRange(startOffset, textToStream.Length);
```

2021-11-23 22:44 UTC, scottaddie commented on FileStorage/GettingStarted.cs
> +                    HttpRange range = new HttpRange(startOffset, textToStream.Length);
```suggestion
                    var range = new HttpRange(startOffset, textToStream.Length);
```

2021-11-24 01:37 UTC, Tianyun-G commented
@scottaddie - I have updated , please review.

2021-11-24 03:14 UTC, scottaddie approved these changes

2021-11-30 02:50 UTC, v-xuto commented
@jongio Please help to merge this PR.

2021-12-01 01:55 UTC, merged